/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tablajava;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author gamba
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public  Consulta() {
        initComponents();
        actualizarTabla();
        
    }
    
 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void actualizarTabla() {
        DefaultTableModel modeloDefault = new DefaultTableModel(new String[] {"Animal", "Numero","Vacunacion", "Produccion", "Comentarios"}, 0);
        tabla.setModel(modeloDefault);

        for (Animal animal : TablaJava.animales) {
            modeloDefault.addRow(new Object[]{
                animal.getTipo(),
                animal.getCodigo(),
                animal.getEstadovacuna(),
                animal.getProduccion(),
                animal.getComentario()
            });
        }
    }
        
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelPrincipal = new javax.swing.JPanel();
        PanelIzda = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelDerecha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        PanelIzda.setBackground(new java.awt.Color(0, 153, 51));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(new java.awt.BorderLayout());

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/LogoEmpresa.png"))); // NOI18N
        jPanel4.add(Imagen, java.awt.BorderLayout.CENTER);

        jLabel6.setText("    ");
        jPanel4.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jLabel7.setText("    ");
        jPanel4.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel8.setText("    ");
        jPanel4.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel9.setText("    ");
        jPanel4.add(jLabel9, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout PanelIzdaLayout = new javax.swing.GroupLayout(PanelIzda);
        PanelIzda.setLayout(PanelIzdaLayout);
        PanelIzdaLayout.setHorizontalGroup(
            PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzdaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelIzdaLayout.setVerticalGroup(
            PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzdaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        PanelPrincipal.add(PanelIzda);

        PanelDerecha.setBackground(new java.awt.Color(0, 153, 51));
        PanelDerecha.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("    ");
        PanelDerecha.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jLabel3.setText("    ");
        PanelDerecha.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setText("    ");
        PanelDerecha.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jLabel5.setText("     ");
        PanelDerecha.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Animal", "Numero", "Vacunacion", "Produccion", "Comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tablaComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        PanelDerecha.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(PanelDerecha);

        jMenu1.setText("Menu");

        jMenu2.setText("Añadir Animal");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
         IngresoAnimales ventana = new IngresoAnimales();
        ventana.setVisible(true);
        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                actualizarTabla(); // Actualiza la tabla al cerrar la ventana de ingreso
            }
        });
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void tablaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tablaComponentAdded
        DefaultTableModel modeloDefault = new DefaultTableModel(new String []{"Animal", "Numero", "Poduccion", "Comentarios"},TablaJava.animales.size());
        tabla.setModel(modeloDefault);
        
        TableModel modeloDatos = tabla.getModel();
        for(int i = 0; i< TablaJava.animales.size(); i++){
        Animal animal = TablaJava.animales.get(i);
        modeloDatos.setValueAt(animal.getTipo(),i,0);
        modeloDatos.setValueAt(animal.getCodigo(),i,1);
        modeloDatos.setValueAt(animal.getEstadovacuna(),i,2);
        modeloDatos.setValueAt(animal.getProduccion(),i,3);
        modeloDatos.setValueAt(animal.getComentario(),i,4);
        }
    }//GEN-LAST:event_tablaComponentAdded

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzda;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
