/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tablajava;

import java.util.Set;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import static tablajava.TablaJava.animales;

/**
 *
 * @author gamba
 */
public class IngresoAnimales extends javax.swing.JFrame {

    /**
     * Creates new form IngresoAnimales
     */
    public IngresoAnimales() {
        initComponents();
         // Configuración de los botones de opción de vacunación
    jRadioButton1.setText("Vacunado");
    jRadioButton1.setActionCommand("Vacunado"); // Asigna el comando
    buttonGroup1.add(jRadioButton1);

    jRadioButton2.setText("En vacunación");
    jRadioButton2.setActionCommand("En vacunación"); // Asigna el comando
    buttonGroup1.add(jRadioButton2);

    jRadioButton3.setText("No vacunado");
    jRadioButton3.setActionCommand("No vacunado"); // Asigna el comando
    buttonGroup1.add(jRadioButton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        PanelIzda = new javax.swing.JPanel();
        TextoTipo = new javax.swing.JLabel();
        TextoCodigo = new javax.swing.JLabel();
        TextoEstadoVac = new javax.swing.JLabel();
        TextoProduce = new javax.swing.JLabel();
        TextoComentario = new javax.swing.JLabel();
        BotonAcceptar = new javax.swing.JButton();
        produce = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        tipo = new javax.swing.JComboBox<>();
        numero = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        BotonCerrar = new javax.swing.JButton();
        PanelDerecha = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(51, 204, 0));
        PanelPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        PanelIzda.setBackground(new java.awt.Color(0, 153, 51));
        PanelIzda.setForeground(new java.awt.Color(0, 204, 102));

        TextoTipo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoTipo.setForeground(new java.awt.Color(255, 255, 255));
        TextoTipo.setText("Tipo animal");

        TextoCodigo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        TextoCodigo.setText("Codigo unico");

        TextoEstadoVac.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoEstadoVac.setForeground(new java.awt.Color(255, 255, 255));
        TextoEstadoVac.setText("Estado de Vacunación");

        TextoProduce.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoProduce.setForeground(new java.awt.Color(255, 255, 255));
        TextoProduce.setText("En producción");

        TextoComentario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TextoComentario.setForeground(new java.awt.Color(255, 255, 255));
        TextoComentario.setText("Comentarios");

        BotonAcceptar.setBackground(new java.awt.Color(204, 255, 204));
        BotonAcceptar.setText("Acceptar");
        BotonAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcceptarActionPerformed(evt);
            }
        });

        produce.setBackground(new java.awt.Color(0, 153, 51));
        produce.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        produce.setForeground(new java.awt.Color(255, 255, 255));
        produce.setText("Produce");

        comentario.setColumns(20);
        comentario.setRows(5);
        jScrollPane1.setViewportView(comentario);

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Vacunado");

        jRadioButton2.setBackground(new java.awt.Color(0, 153, 51));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("En vacunacion");

        jRadioButton3.setBackground(new java.awt.Color(0, 153, 51));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("No vacunado");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vaca", "Cerdo", "Oveja", "Cabra" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        BotonCerrar.setBackground(new java.awt.Color(204, 255, 204));
        BotonCerrar.setText("Cerrar");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIzdaLayout = new javax.swing.GroupLayout(PanelIzda);
        PanelIzda.setLayout(PanelIzdaLayout);
        PanelIzdaLayout.setHorizontalGroup(
            PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzdaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelIzdaLayout.createSequentialGroup()
                            .addComponent(TextoComentario)
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TextoCodigo)
                        .addGroup(PanelIzdaLayout.createSequentialGroup()
                            .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextoEstadoVac)
                                .addComponent(TextoProduce, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelIzdaLayout.createSequentialGroup()
                                    .addComponent(TextoTipo)
                                    .addGap(44, 44, 44)))
                            .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PanelIzdaLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton2)
                                        .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(numero)
                                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jRadioButton1))
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIzdaLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(produce)
                                    .addGap(19, 19, 19)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIzdaLayout.createSequentialGroup()
                        .addComponent(BotonCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAcceptar)))
                .addContainerGap())
        );
        PanelIzdaLayout.setVerticalGroup(
            PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzdaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIzdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoTipo))
                .addGap(24, 24, 24)
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCodigo))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(TextoEstadoVac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelIzdaLayout.createSequentialGroup()
                        .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produce)
                            .addComponent(TextoProduce))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextoComentario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(PanelIzdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAcceptar)
                    .addComponent(BotonCerrar))
                .addGap(48, 48, 48))
        );

        PanelPrincipal.add(PanelIzda);

        PanelDerecha.setBackground(new java.awt.Color(0, 153, 51));
        PanelDerecha.setLayout(new java.awt.BorderLayout());
        PanelDerecha.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jLabel13.setText("                         ");
        PanelDerecha.add(jLabel13, java.awt.BorderLayout.LINE_START);
        PanelDerecha.add(jLabel14, java.awt.BorderLayout.PAGE_END);
        PanelDerecha.add(jLabel15, java.awt.BorderLayout.LINE_END);

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descarga.jpg"))); // NOI18N
        PanelDerecha.add(Imagen, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(PanelDerecha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcceptarActionPerformed

        
        
        //Tipo
        String especie = tipo.getSelectedItem().toString();
        //Numero
        int num = (int) numero.getValue();
        //Estado vacuna
        ButtonModel estadoVacunacionModel = buttonGroup1.getSelection();
        String estadoVacunacion = (estadoVacunacionModel != null) ? estadoVacunacionModel.getActionCommand() : "No seleccionado";
        System.out.println("Estado de vacunación: " + estadoVacunacion);

        //Produccion
        boolean enProduccion = produce.isSelected();
        //Comentario
        String coment = comentario.getText();
        
        System.out.print(estadoVacunacion);
        
      
        
        
        if(estadoVacunacionModel == null) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un estado de vacunacion", "Registro Denegado", JOptionPane.INFORMATION_MESSAGE);
        } else {
  
            Animal animal = new Animal (especie, num, estadoVacunacion, enProduccion, coment);
        TablaJava.animales.add(animal);
         JOptionPane.showMessageDialog(null, "Animal registrado", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        comentario.setText("");
        }
        
       
        
    }//GEN-LAST:event_BotonAcceptarActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAcceptar;
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzda;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel TextoCodigo;
    private javax.swing.JLabel TextoComentario;
    private javax.swing.JLabel TextoEstadoVac;
    private javax.swing.JLabel TextoProduce;
    private javax.swing.JLabel TextoTipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea comentario;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner numero;
    private javax.swing.JCheckBox produce;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
